### ISSUE TITLE
Tests fails "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by blaryjp** [K-Phoen/backstage-plugin-opsgenie#42]
Hello,

I updated all Backstage with last version of all deps, and I have an error when I run "yarn test" on Backstage:

```
    /workspace/backstage-app/node_modules/@k-phoen/backstage-plugin-opsgenie/dist/esm/index-d8881c5c.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { createApiRef, createRouteRef, createPlugin, createApiFactory, discoveryApiRef, identityApiRef, configApiRef, createRoutableExtension, createComponentExtension } from '@backstage/core-plugin-api';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (../../../node_modules/@k-phoen/backstage-plugin-opsgenie/dist/index.esm.js:49:22)

```

Do you have the same issue on your side?

Thank you,

**Comment by K-Phoen** [comment]
Hej,

I do not have the same issue, no. Have you tried with the latest version of this package? (I cleaned the building/publishing pipeline)

**Comment by blaryjp** [comment]
Hello,

I update with your last version (0.4.5), and I don't have the problem anymore. The problem persists with version 0.4.3.

Anyway, it is fixed for me by updating the plugin, so it's ok. Thank you :).
